### ISSUE TITLE
Typos in inverse hyperbolic functions

### ISSUE THREAD

**Issue by DrVaitkus** [HQSquantumsimulations/qoqo_calculator#3]
Should be asinh
https://github.com/HQSquantumsimulations/qoqo_calculator/blob/6d7d0e708bdb3b5a4990e4b90032aabae9268ad9/src/calculator.rs#L86

Should be atanh
https://github.com/HQSquantumsimulations/qoqo_calculator/blob/6d7d0e708bdb3b5a4990e4b90032aabae9268ad9/src/calculator.rs#L87

**Comment by nfwvogt** [comment]
Absolutely, thanks for the catch!
